<?php

namespace SmartDonusum\EArchive;

use SmartDonusum\EArchive\Type;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;

class EArchiveClassmap
{
    public static function getCollection(): \Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('getPrefixList', Type\GetPrefixList::class),
            new ClassMap('getPrefixListResponse', Type\GetPrefixListResponse::class),
            new ClassMap('DocumentQueryResponse', Type\DocumentQueryResponse::class),
            new ClassMap('ResponseDocument', Type\ResponseDocument::class),
            new ClassMap('DocumentInfo', Type\DocumentInfo::class),
            new ClassMap('TaxInfo', Type\TaxInfo::class),
            new ClassMap('sendInvoiceWithoutId', Type\SendInvoiceWithoutId::class),
            new ClassMap('InputDocument', Type\InputDocument::class),
            new ClassMap('sendInvoiceWithoutIdResponse', Type\SendInvoiceWithoutIdResponse::class),
            new ClassMap('EntResponse', Type\EntResponse::class),
            new ClassMap('sendInvoiceWithoutIdAndUuid', Type\SendInvoiceWithoutIdAndUuid::class),
            new ClassMap('sendInvoiceWithoutIdAndUuidResponse', Type\SendInvoiceWithoutIdAndUuidResponse::class),
            new ClassMap('addPrefixList', Type\AddPrefixList::class),
            new ClassMap('PrefixCode', Type\PrefixCode::class),
            new ClassMap('addPrefixListResponse', Type\AddPrefixListResponse::class),
            new ClassMap('PrefixCodeResponse', Type\PrefixCodeResponse::class),
            new ClassMap('GetXsltList', Type\GetXsltList::class),
            new ClassMap('GetXsltListResponse', Type\GetXsltListResponse::class),
            new ClassMap('XsltListResponse', Type\XsltListResponse::class),
            new ClassMap('XsltResponse', Type\XsltResponse::class),
            new ClassMap('QueryArchivedInvoice', Type\QueryArchivedInvoice::class),
            new ClassMap('QueryArchivedInvoiceResponse', Type\QueryArchivedInvoiceResponse::class),
            new ClassMap('QueryInvoicesWithReceivedDateWithSearchParams', Type\QueryInvoicesWithReceivedDateWithSearchParams::class),
            new ClassMap('searchParams', Type\SearchParams::class),
            new ClassMap('entry', Type\Entry::class),
            new ClassMap('QueryInvoicesWithReceivedDateWithSearchParamsResponse', Type\QueryInvoicesWithReceivedDateWithSearchParamsResponse::class),
            new ClassMap('QueryInvoicesWithGUIDList', Type\QueryInvoicesWithGUIDList::class),
            new ClassMap('QueryInvoicesWithGUIDListResponse', Type\QueryInvoicesWithGUIDListResponse::class),
            new ClassMap('sendZReport', Type\SendZReport::class),
            new ClassMap('sendZReportResponse', Type\SendZReportResponse::class),
            new ClassMap('setPrefixStatusList', Type\SetPrefixStatusList::class),
            new ClassMap('PrefixCodeStatus', Type\PrefixCodeStatus::class),
            new ClassMap('setPrefixStatusListResponse', Type\SetPrefixStatusListResponse::class),
            new ClassMap('UploadXslt', Type\UploadXslt::class),
            new ClassMap('UploadXsltPayload', Type\UploadXsltPayload::class),
            new ClassMap('UploadXsltResponse', Type\UploadXsltResponse::class),
            new ClassMap('updateInvoice', Type\UpdateInvoice::class),
            new ClassMap('updateInvoiceResponse', Type\UpdateInvoiceResponse::class),
            new ClassMap('GetLastInvoiceIdAndDate', Type\GetLastInvoiceIdAndDate::class),
            new ClassMap('GetLastInvoiceIdAndDateResponse', Type\GetLastInvoiceIdAndDateResponse::class),
            new ClassMap('QueryInvoice', Type\QueryInvoice::class),
            new ClassMap('QueryInvoiceResponse', Type\QueryInvoiceResponse::class),
            new ClassMap('QueryArchivedInvoicesWithDocumentDate', Type\QueryArchivedInvoicesWithDocumentDate::class),
            new ClassMap('QueryArchivedInvoicesWithDocumentDateResponse', Type\QueryArchivedInvoicesWithDocumentDateResponse::class),
            new ClassMap('setDocumentFlag', Type\SetDocumentFlag::class),
            new ClassMap('flagSetter', Type\FlagSetter::class),
            new ClassMap('setDocumentFlagResponse', Type\SetDocumentFlagResponse::class),
            new ClassMap('QueryInvoiceWithReferenceCode', Type\QueryInvoiceWithReferenceCode::class),
            new ClassMap('QueryInvoiceWithReferenceCodeResponse', Type\QueryInvoiceWithReferenceCodeResponse::class),
            new ClassMap('controlInvoiceXML', Type\ControlInvoiceXML::class),
            new ClassMap('controlInvoiceXMLResponse', Type\ControlInvoiceXMLResponse::class),
            new ClassMap('sendSignedInvoice', Type\SendSignedInvoice::class),
            new ClassMap('sendSignedInvoiceResponse', Type\SendSignedInvoiceResponse::class),
            new ClassMap('GetEAInvoiceStatusWithLogs', Type\GetEAInvoiceStatusWithLogs::class),
            new ClassMap('GetEAInvoiceStatusWithLogsResponse', Type\GetEAInvoiceStatusWithLogsResponse::class),
            new ClassMap('logResponse', Type\LogResponse::class),
            new ClassMap('UpdateXslt', Type\UpdateXslt::class),
            new ClassMap('UpdateXsltResponse', Type\UpdateXsltResponse::class),
            new ClassMap('SetDefaultXslt', Type\SetDefaultXslt::class),
            new ClassMap('SetDefaultXsltResponse', Type\SetDefaultXsltResponse::class),
            new ClassMap('QueryInvoicesWithDocumentDateAndSearchParams', Type\QueryInvoicesWithDocumentDateAndSearchParams::class),
            new ClassMap('QueryInvoicesWithDocumentDateAndSearchParamsResponse', Type\QueryInvoicesWithDocumentDateAndSearchParamsResponse::class),
            new ClassMap('GetDraftDocumentPreview', Type\GetDraftDocumentPreview::class),
            new ClassMap('GetDraftDocumentPreviewResponse', Type\GetDraftDocumentPreviewResponse::class),
            new ClassMap('QueryInvoiceWithLocalId', Type\QueryInvoiceWithLocalId::class),
            new ClassMap('QueryInvoiceWithLocalIdResponse', Type\QueryInvoiceWithLocalIdResponse::class),
            new ClassMap('setEmailSent', Type\SetEmailSent::class),
            new ClassMap('setEmailSentResponse', Type\SetEmailSentResponse::class),
            new ClassMap('ResendNotification', Type\ResendNotification::class),
            new ClassMap('ResendNotificationPayload', Type\ResendNotificationPayload::class),
            new ClassMap('ResendNotificationResponse', Type\ResendNotificationResponse::class),
            new ClassMap('DeleteXslt', Type\DeleteXslt::class),
            new ClassMap('DeleteXsltResponse', Type\DeleteXsltResponse::class),
            new ClassMap('sendAndApproveInvoice', Type\SendAndApproveInvoice::class),
            new ClassMap('sendAndApproveInvoiceResponse', Type\SendAndApproveInvoiceResponse::class),
            new ClassMap('getCustomerCreditCount', Type\GetCustomerCreditCount::class),
            new ClassMap('getCustomerCreditCountResponse', Type\GetCustomerCreditCountResponse::class),
            new ClassMap('CreditInfo', Type\CreditInfo::class),
            new ClassMap('getNewUUID', Type\GetNewUUID::class),
            new ClassMap('getNewUUIDResponse', Type\GetNewUUIDResponse::class),
            new ClassMap('QueryInvoicesWithReceivedDate', Type\QueryInvoicesWithReceivedDate::class),
            new ClassMap('QueryInvoicesWithReceivedDateResponse', Type\QueryInvoicesWithReceivedDateResponse::class),
            new ClassMap('isEFaturaUser', Type\IsEFaturaUser::class),
            new ClassMap('isEFaturaUserResponse', Type\IsEFaturaUserResponse::class),
            new ClassMap('UserQueryResponse', Type\UserQueryResponse::class),
            new ClassMap('ResponseUser', Type\ResponseUser::class),
            new ClassMap('getCustomerCreditSpace', Type\GetCustomerCreditSpace::class),
            new ClassMap('getCustomerCreditSpaceResponse', Type\GetCustomerCreditSpaceResponse::class),
            new ClassMap('sendInvoice', Type\SendInvoice::class),
            new ClassMap('sendInvoiceResponse', Type\SendInvoiceResponse::class),
            new ClassMap('cancelInvoice', Type\CancelInvoice::class),
            new ClassMap('cancelInvoiceResponse', Type\CancelInvoiceResponse::class),
            new ClassMap('objectInvoice', Type\ObjectInvoice::class),
            new ClassMap('objectInvoiceResponse', Type\ObjectInvoiceResponse::class),
            new ClassMap('QueryInvoicesWithDocumentDate', Type\QueryInvoicesWithDocumentDate::class),
            new ClassMap('QueryInvoicesWithDocumentDateResponse', Type\QueryInvoicesWithDocumentDateResponse::class),
            new ClassMap('getCreditActionsforCustomer', Type\GetCreditActionsforCustomer::class),
            new ClassMap('getCreditActionsforCustomerResponse', Type\GetCreditActionsforCustomerResponse::class),
            new ClassMap('CreditAction', Type\CreditAction::class),
        );
    }
}

