<?php

namespace SmartDonusum\EInvoice;

use SmartDonusum\EInvoice\Type;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;

class EInvoiceClassmap
{
    public static function getCollection(): \Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('DeleteXslt', Type\DeleteXslt::class),
            new ClassMap('DeleteXsltResponse', Type\DeleteXsltResponse::class),
            new ClassMap('EntResponse', Type\EntResponse::class),
            new ClassMap('getCustomerCreditCount', Type\GetCustomerCreditCount::class),
            new ClassMap('getCustomerCreditCountResponse', Type\GetCustomerCreditCountResponse::class),
            new ClassMap('CreditInfo', Type\CreditInfo::class),
            new ClassMap('sendAppResponse', Type\SendAppResponse::class),
            new ClassMap('sendAppResponseResponse', Type\SendAppResponseResponse::class),
            new ClassMap('getNewUUID', Type\GetNewUUID::class),
            new ClassMap('getNewUUIDResponse', Type\GetNewUUIDResponse::class),
            new ClassMap('sendAppResponseList', Type\SendAppResponseList::class),
            new ClassMap('AppResponseDocument', Type\AppResponseDocument::class),
            new ClassMap('sendAppResponseListResponse', Type\SendAppResponseListResponse::class),
            new ClassMap('getCustomerCreditSpace', Type\GetCustomerCreditSpace::class),
            new ClassMap('getCustomerCreditSpaceResponse', Type\GetCustomerCreditSpaceResponse::class),
            new ClassMap('getUserAliases', Type\GetUserAliases::class),
            new ClassMap('getUserAliasesResponse', Type\GetUserAliasesResponse::class),
            new ClassMap('UserAddresInfo', Type\UserAddresInfo::class),
            new ClassMap('sendInvoice', Type\SendInvoice::class),
            new ClassMap('InputDocument', Type\InputDocument::class),
            new ClassMap('sendInvoiceResponse', Type\SendInvoiceResponse::class),
            new ClassMap('cancelInvoice', Type\CancelInvoice::class),
            new ClassMap('cancelInvoiceResponse', Type\CancelInvoiceResponse::class),
            new ClassMap('GetOutboxInvoiceStatusWithLogs', Type\GetOutboxInvoiceStatusWithLogs::class),
            new ClassMap('GetOutboxInvoiceStatusWithLogsResponse', Type\GetOutboxInvoiceStatusWithLogsResponse::class),
            new ClassMap('logResponse', Type\LogResponse::class),
            new ClassMap('getCreditActionsforCustomer', Type\GetCreditActionsforCustomer::class),
            new ClassMap('getCreditActionsforCustomerResponse', Type\GetCreditActionsforCustomerResponse::class),
            new ClassMap('CreditAction', Type\CreditAction::class),
            new ClassMap('controlInvoiceXML', Type\ControlInvoiceXML::class),
            new ClassMap('controlInvoiceXMLResponse', Type\ControlInvoiceXMLResponse::class),
            new ClassMap('sendSignedInvoice', Type\SendSignedInvoice::class),
            new ClassMap('sendSignedInvoiceResponse', Type\SendSignedInvoiceResponse::class),
            new ClassMap('controlApplicationResponseXML', Type\ControlApplicationResponseXML::class),
            new ClassMap('controlApplicationResponseXMLResponse', Type\ControlApplicationResponseXMLResponse::class),
            new ClassMap('UpdateXslt', Type\UpdateXslt::class),
            new ClassMap('UpdateXsltResponse', Type\UpdateXsltResponse::class),
            new ClassMap('sendApplicationResponse', Type\SendApplicationResponse::class),
            new ClassMap('sendApplicationResponseResponse', Type\SendApplicationResponseResponse::class),
            new ClassMap('SetDefaultXslt', Type\SetDefaultXslt::class),
            new ClassMap('SetDefaultXsltResponse', Type\SetDefaultXsltResponse::class),
            new ClassMap('GetDraftDocumentPreview', Type\GetDraftDocumentPreview::class),
            new ClassMap('GetDraftDocumentPreviewResponse', Type\GetDraftDocumentPreviewResponse::class),
            new ClassMap('updateInvoice', Type\UpdateInvoice::class),
            new ClassMap('updateInvoiceResponse', Type\UpdateInvoiceResponse::class),
            new ClassMap('setDocumentFlag', Type\SetDocumentFlag::class),
            new ClassMap('flagSetter', Type\FlagSetter::class),
            new ClassMap('setDocumentFlagResponse', Type\SetDocumentFlagResponse::class),
            new ClassMap('getCustomerPKList', Type\GetCustomerPKList::class),
            new ClassMap('getCustomerPKListResponse', Type\GetCustomerPKListResponse::class),
            new ClassMap('UserQueryResponse', Type\UserQueryResponse::class),
            new ClassMap('ResponseUser', Type\ResponseUser::class),
            new ClassMap('saveToTaslak', Type\SaveToTaslak::class),
            new ClassMap('saveToTaslakResponse', Type\SaveToTaslakResponse::class),
            new ClassMap('getPrefixList', Type\GetPrefixList::class),
            new ClassMap('getPrefixListResponse', Type\GetPrefixListResponse::class),
            new ClassMap('DocumentQueryResponse', Type\DocumentQueryResponse::class),
            new ClassMap('ResponseDocument', Type\ResponseDocument::class),
            new ClassMap('DocumentInfo', Type\DocumentInfo::class),
            new ClassMap('TaxInfo', Type\TaxInfo::class),
            new ClassMap('getCustomerGBList', Type\GetCustomerGBList::class),
            new ClassMap('getCustomerGBListResponse', Type\GetCustomerGBListResponse::class),
            new ClassMap('addPrefixList', Type\AddPrefixList::class),
            new ClassMap('PrefixCode', Type\PrefixCode::class),
            new ClassMap('addPrefixListResponse', Type\AddPrefixListResponse::class),
            new ClassMap('PrefixCodeResponse', Type\PrefixCodeResponse::class),
            new ClassMap('sendInvoiceWithoutDocumentId', Type\SendInvoiceWithoutDocumentId::class),
            new ClassMap('sendInvoiceWithoutDocumentIdResponse', Type\SendInvoiceWithoutDocumentIdResponse::class),
            new ClassMap('GetXsltList', Type\GetXsltList::class),
            new ClassMap('GetXsltListResponse', Type\GetXsltListResponse::class),
            new ClassMap('XsltListResponse', Type\XsltListResponse::class),
            new ClassMap('XsltResponse', Type\XsltResponse::class),
            new ClassMap('uploadInvoiceList', Type\UploadInvoiceList::class),
            new ClassMap('uploadInvoiceListResponse', Type\UploadInvoiceListResponse::class),
            new ClassMap('setPrefixStatusList', Type\SetPrefixStatusList::class),
            new ClassMap('PrefixCodeStatus', Type\PrefixCodeStatus::class),
            new ClassMap('setPrefixStatusListResponse', Type\SetPrefixStatusListResponse::class),
            new ClassMap('ResendDocument', Type\ResendDocument::class),
            new ClassMap('ResendDocumentResponse', Type\ResendDocumentResponse::class),
            new ClassMap('UploadXslt', Type\UploadXslt::class),
            new ClassMap('UploadXsltPayload', Type\UploadXsltPayload::class),
            new ClassMap('UploadXsltResponse', Type\UploadXsltResponse::class),
        );
    }
}

